# 🌟Module 6: Function Through The Lens of ML🌟

# Function:

* function is a set of instruction
* function -> instructions -> output

# Types of function:
* Built in function
* User define function

# User-defined function structure:  
```
 def->function name->(parameters/argument):  
 
   ----  instructions ----  

     return type  
     
 
 ```

In [2]:
#### No parameter, no return type function example ####

def print_message(): # function define 
    print("Hello Everyone") # instruction 
    
print_message()    # function call

Hello Everyone

In [1]:
def welcome_message(user): # here 'user' is a parameter 
    print(f"Hello {user}")

welcome_message("Dipu")

Hello Dipu

In [7]:
def welcome_message (user = "None"): # If I don't send any parameter, then it will print "none"
    print(user)


welcome_mesage()
welcome_message("Dipu")

None
Dipu

In [10]:
def adder(a,b):
    sum = a + b
    print(sum)

m = adder(10,12) * 5 # Here we get an error because the adder function is not returning anything; the function is just printing the addition of two numbers  
print(m)

22

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

In [11]:
def adder(a,b):
    sum = a + b
    return sum

m = adder(10,12) * 5 # Here we get an error because the adder function is not returning anything; the function is just printing the addition of two numbers  
print(m)

110

# 'doc' in function:

In [21]:
def adder(a,b):
    """ 
    The function is adding two nubmers  
    
    """
    sum = a + b
    return sum
    

m = adder(10,12) * 5
print(m)
help(adder) # help function gives the description of the function and prints the doc of the function
#help(print)

110
Help on function adder in module __main__:

adder(a, b)
    The function is adding two nubmers

# N:B  
* Parameter: A variable defined in a function to receive a value when the function is called.  
* Argument: The actual value passed to a function when calling it.  
Example:  
```py
def adder(a, b):  # a and b are parameters
    return a + b

adder(10, 20)     # 10 and 20 are arguments
```

# Different types of Arguments:
* Positional argument
* Keyword

## Positional Arguments:

In [22]:
def add(a,b):  
    print(a, b)
add(1,64) # here 1 and 64 are positional argument

1 64

In [1]:
def add(*args):  
    print(args)
    for i in args:
        print(i)
    print(*args)
    
add(1,64,34,5,35)

(1, 64, 34, 5, 35)
1
64
34
5
35
1 64 34 5 35

## Keyword arguments:

In [ ]:
def show(a,b,c):
    print(f"{a} {b} {c}")

show(a = 10, c = 30, b = 40) # These are key word arguments were the arguments is assigned

10 40 30

In [ ]:
def show(**args):
    print(args)
    for key, value in args.items():
        print(key, value)
    
show(a = 34, c = 53, b = 34) # it shows data in a dictionary attributes

{'a': 34, 'c': 53, 'b': 34}
a 34
c 53
b 34

# Return Type of a functions:

In [39]:
#### Integer return type function ####
def return_integer(a):
    return a

print(type(return_integer(10)))

<class 'int'>

In [42]:
#### float return type function ####
def return_float(a):
    return a

print(type(return_integer(10.5)))

<class 'float'>

In [43]:
#### String return type function ####
def return_string(a):
    return a

print(type(return_integer("Dipu")))

<class 'str'>

In [45]:
#### tuple return type function ####
def return_tuple(a,b):
    return a, b

print(type(return_integer(10.3, "Dipu"))) # return as a tuple type

x,y = return_integer(334,64) # unzip version of the tuple ruturn type
print(x,y)

<class 'tuple'>
334 64

# Iterator and Generator

## Iterator:

In [46]:
s = {1, 2, 5, 6, 6}
print(s[1]) # set can not access by indexing

TypeError: 'set' object is not subscriptable

In [3]:
s = {1, 2, 5, 6, 6}
s_iter = iter(s) # iter function is an iterator 
print(type(s_iter))
print(s_iter)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

<class 'set_iterator'>
<set_iterator object at 0x00000161D59BAB40>
1
2
5
6

In [63]:
dictionary = {1:13, 34: "Dipu", 4.6: "hablu"}
dic_iter = iter(dictionary)
print(type(dic_iter))
print(dic_iter) # printing the location of the iterator object
print(next(dic_iter))
key = next(dic_iter)
print(key, dictionary[key])

<class 'dict_keyiterator'>
<dict_keyiterator object at 0x00000171E93BE660>
1
34 Dipu

# Generator: get data as a chunk size

In [73]:
lst = [x for x in range(500)] # dataset

def data_loader(chunk_size, lst):
    for i in range(0,len(lst),chunk_size):
        yield lst[i: i+chunk_size:]

x = data_loader(5,lst)
print(type(x)) # the data type will give generator
print(x)
print(next(x))
print(next(x))

<class 'generator'>
<generator object data_loader at 0x00000171E915D3F0>
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

# Lambda, Map and Apply function

In [74]:
import pandas as pd


df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})
df

df['temperature (C)'] = df['temperature (F)'].apply(lambda x: (x - 32) * 5/9)
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [75]:
def adder(a,b) :
  return [a,b]

print(type(adder(10.5,20)))

#unzip

x,y = adder(10.5,20)

print(y)

<class 'list'>
20

In [76]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})

df

df['A'] = df['A'].apply(lambda x: x ** 0.5)


df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [77]:
import pandas as pd

df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x > 500 else 0)

df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1

# N:B: This section is collected form an ai  

Remember this rule: 
- map() → transform each element.
- filter() → keep elements that satisfy a condition.
- reduce() → combine elements into a single result.

# Some Extra Practice problems: [The Link](https://docs.google.com/document/d/1A6ZSbwLAkccHo85bWu5cCAeEMty9dceZPvGHCZopVMo/edit?tab=t.0)

#### Problem A. The Homework Bot (Easy) solution:
```python
def check_pass(marks):
    """Return True if the student passes the quiz."""
    return marks >= 40

marks = int(input())

if check_pass(marks):
    print("Pass")
else:
    print("Fail")
```

#### Problem B. Three Training Runs (Easy) solution:
```python
def mean(a, b, c):
    result = (a + b + c) / 3
    return result

a,b,c = [float(x) for x in input().split()]
result = mean(a,b,c)
print(result)  
```

#### Problem C. New Interns at the AI Lab (Easy) solution:
```py
def new_intern(name, roll, dept):
    print(f"{name} | Roll: {roll} | Dept: {dept}")

for x in range(2):
    name,roll,dept = [x for x in input().split()]
    new_intern(name,roll,dept)

```

#### Problem D. The Model Registry (Medium) solution:
```python
def model_info(name, layer, lr = 0.01):
    return f"model: {name}, Layers: {layer}, LR: {lr}"

t = int(input())

while t>0:
    lst = [x for x in input().split()]
    type = int(lst[0])
    if type == 1 :
        name  = lst[1]
        layers = lst[2]
        print(model_info(name, layers))
    elif type == 2:
        name = lst[1]
        layers = lst[2]
        print(model_info(layer = layers, name = name))
    else: 
        name = lst[1]
        layers = lst[2]
        Lr = lst[3]
        print(model_info(name, layers, Lr))
    t -= 1

           


```

#### Problem E. Clean Images, Then Features (Medium) solution:
```python
n = int(input())

lst = [int(x) for x in input().split()]

even_lst = list(map(lambda x : x*x, filter(lambda x : x%2 == 0, lst)))

print(even_lst)
```

#### Problem F. GPU Can Eat Only Three Images (Hard) solution:
```python
from functools import reduce
def batch_generator(lst, batch_size):
    for i in range(0,len(lst),batch_size):
        yield lst[i: batch_size+i:]

n,batch_size = [int(x) for x in input().split()]
lst = [int(x) for x in input().split()]
for i in batch_generator(lst,batch_size):
    total = reduce(lambda x,y: x+y, i)
    mean = total/len(i)
    print(f"{i} mean={mean}")
```

# More Extra Problems

### Problem 1:  
----
Write a function introduce(name, age) that prints:

My name is <name> and I am <age> years old.
 
Call it using positional arguments.

Sample Input:  

Rahim 28  

Sample Output:  

My name is Rahim and I am 28 years old.

### solution code:  
```python
def name_age(name, age):
    print(f"My name is {name} and I am {age} years old.")

name, age = [x for x in input().split()]
name_age(name,age)
```

### Problem 2: 
---
Write a Python generator function called batch_generator. It should take a list of numbers (representing data samples) and a batch_size. The generator should yield one batch at a time as a list.

Example Input:  

data = [1, 2, 3, 4, 5, 6, 7, 8]  

batch_size = 3


Expected Output (when iterated):  

[1, 2, 3]  

[4, 5, 6]  

[7, 8]

### solution code:
```python
def data_load(lst, batch_size):
    for i in range(0, len(lst), batch_size):
        yield lst[i:batch_size+i]

data = [int(x) for x in input("data = ").split()]
n = int(input("batch_size = "))

for i in data_load(data,n):
    print(i)
```

### Problem 3:
---

Given a list [1,2,3,4], use map() and lambda to create a new list with squares of each number.

Sample Input:  

 No input

Sample Output:  

[1, 4, 9, 16]

### solution code:
```python
lst = [1,2,3,4]
new_lst = list(map(lambda x:x*x, lst))
print(new_lst)
```

### Problem 4: 
---
Write a function power(base, exponent) that returns the result of base raised to exponent. If the exponent is not given, it should calculate the square.  

Sample Input:  

5  

Sample Output:  

25  

Sample Input 2:  

5 3  

Sample Output 2:  

125

### solution code:
```python
def power(base, exponent = 2):
    result = 1
    for i in range(exponent):
        result *= base
    return result

nums = [int(x) for x in input().split()]
if len(nums) == 1:
    print(power(nums[0]))
else: print(power(nums[0],nums[1]))
```

### Problem 5:
----

 Given a list [1,2,3,4,5,6], use filter() to select even numbers and map() with lambda to square them.  

Sample Input:  

 No input  

Sample Output:  

[4, 16, 36]

### solution code:
```python


given  = [1,2,3,4,5,6]
new_lst = list(map(lambda x:x*x, filter(lambda x: x%2 == 0, given)))
print(new_lst)
```